#! /bin/bash

base_dir=$HOME/files
config_dir=$HOME/.config

# STANDARD MODE
## INCLUDE FILES
    source_file[0]=$base_dir/config/linux/xterm/Xresources
    target_file[0]=$HOME/.Xresources

    source_file[1]=$base_dir/config/linux/mailcap
    target_file[1]=$HOME/.mailcap

    source_file[2]=$base_dir/config/linux/xinitrc
    target_file[2]=$HOME/.xinitrc

## INCLUDE DIRS
### Config
    source_dir[0]=$base_dir/config/linux/mutt/
    target_dir[0]=$HOME/.mutt/
    alias_dir[0]="mutt"

    source_dir[1]=$base_dir/config/linux/i3/
    target_dir[1]=$config_dir/i3/
    alias_dir[1]="i3"

    source_dir[2]=$base_dir/nerd/dev/vim/vimtex-colors.vim/
    target_dir[2]=$base_dir/config/vim/bundle/vimtex-colors.vim/
    alias_dir[2]="vimtex-colors"

    source_dir[3]=$base_dir/nerd/dev/vim/essence.vim/
    target_dir[3]=$base_dir/config/vim/bundle/essence.vim/
    alias_dir[3]="essence-colors"

    source_dir[4]=$HOME/.vim/spell/
    target_dir[4]=$base_dir/config/vim/spell/
    alias_dir[4]="vim-spell"

    source_dir[5]=$base_dir/config/vim/
    target_dir[5]=$HOME/.vim/
    alias_dir[5]="vim"
### Dev
    devdir=$HOME/files/nerd/dev
 
    source_dir[6]=$devdir/sh/ecl.sh/
    target_dir[6]=$config_dir/ecl.sh/
    alias_dir[6]="ecl"

    source_dir[7]=$devdir/sh/trsl.sh/
    target_dir[7]=$config_dir/trsl.sh/
    alias_dir[7]="trsl"

    source_dir[8]=$devdir/sh/cvt.sh/
    target_dir[8]=$config_dir/cvt.sh/
    alias_dir[8]="cvt"

    source_dir[9]=$devdir/sh/sync.sh/
    target_dir[9]=$config_dir/sync.sh/
    alias_dir[9]="sync"

    source_dir[10]=$devdir/sh/pm.sh/
    target_dir[10]=$config_dir/pm.sh/
    alias_dir[10]="pm"

    source_dir[11]=$devdir/sh/bkp.sh/
    target_dir[11]=$config_dir/bkp.sh/
    alias_dir[11]="bkp"

    source_dir[12]=$devdir/sh/sw.sh/
    target_dir[12]=$config_dir/sw.sh/
    alias_dir[12]="sw"

    source_dir[13]=$devdir/sh/web.sh/
    target_dir[13]=$config_dir/web.sh/
    alias_dir[13]="web"

    source_dir[14]=$devdir/sh/pkg.sh/
    target_dir[14]=$config_dir/pkg.sh/
    alias_dir[14]="pkg"

    source_dir[15]=$devdir/sh/menu.sh/
    target_dir[15]=$config_dir/menu.sh/
    alias_dir[15]="menu"

### Bkp
    bkpdir=$HOME/bkp/pcloud

    source_dir[16]=$base_dir/
    target_dir[16]=$bkpdir/files/
    alias_dir[16]="bkp_pcloud"

## EXCLUDE FILES
    exclude_file[0]=""

## EXCLUDE DIRS
    
    exclude_dir[0]=""


# GIT MODE
## base GIT dirs
    git_dir[0]=$HOME/bkp/codeberg
    git_dir[1]=$HOME/bkp/github

## initialized GIT dirs
    git_init_dir[0,0]=${git_dir[0]}/backup

    git_init_dir[1,0]=${git_dir[1]}/config

    git_init_dir[1,1]=${git_dir[1]}/dev
    git_init_dir[1,2]=${git_dir[1]}/sh/bkp.sh
    git_init_dir[1,3]=${git_dir[1]}/sh/cvt.sh
    git_init_dir[1,4]=${git_dir[1]}/sh/ecl.sh
    git_init_dir[1,5]=${git_dir[1]}/sh/emutt.sh
    git_init_dir[1,6]=${git_dir[1]}/sh/pkg.sh
    git_init_dir[1,7]=${git_dir[1]}/sh/pm.sh
    git_init_dir[1,8]=${git_dir[1]}/sh/sw.sh
    git_init_dir[1,9]=${git_dir[1]}/sh/sync.sh
    git_init_dir[1,10]=${git_dir[1]}/sh/menu.sh
    git_init_dir[1,11]=${git_dir[1]}/sh/trsl.sh
    git_init_dir[1,12]=${git_dir[1]}/sh/web.sh
    git_init_dir[1,13]=${git_dir[1]}/vim/essence.vim
    git_init_dir[1,14]=${git_dir[1]}/vim/mpc.vim
    git_init_dir[1,15]=${git_dir[1]}/vim/org.vim
    git_init_dir[1,16]=${git_dir[1]}/vim/vimtex-colors.vim

    git_init_dir[1,17]=${git_dir[1]}/doc
    git_init_dir[1,18]=${git_dir[1]}/math
    git_init_dir[1,19]=${git_dir[1]}/yxm-dev

## remotes (default is the name of the initialized dirs)
    git_remote[0,0]="backup"

    git_remote[1,0]="config"
    git_remote[1,1]="dev"
    git_remote[1,2]="bkp"
    git_remote[1,3]="cvt"
    git_remote[1,4]="ecl"
    git_remote[1,5]="emutt"
    git_remote[1,6]="pkg"
    git_remote[1,7]="pm"
    git_remote[1,8]="sw"
    git_remote[1,9]="sync"
    git_remote[1,10]="menu"
    git_remote[1,11]="trsl"
    git_remote[1,12]="web"
    git_remote[1,13]="essence"
    git_remote[1,14]="mpc"
    git_remote[1,15]="org"
    git_remote[1,16]="vimtex"

    git_remote[1,17]="doc"
    git_remote[1,18]="math"
    git_remote[1,19]="yxm"

## branches    
    git_branch[0,0]="master" 

    git_branch[1,0]="master"
    git_branch[1,1]="master"
    git_branch[1,2]="master"
    git_branch[1,3]="master"
    git_branch[1,4]="master"
    git_branch[1,5]="master"
    git_branch[1,6]="master"
    git_branch[1,7]="master"
    git_branch[1,8]="master"
    git_branch[1,9]="master"
    git_branch[1,10]="master"
    git_branch[1,11]="master"
    git_branch[1,12]="master"
    git_branch[1,13]="master"
    git_branch[1,14]="master"
    git_branch[1,15]="master"
    git_branch[1,16]="master"
    git_branch[1,17]="master"
    git_branch[1,18]="master"
    git_branch[1,19]="master"

## default commit
    git_commit[0,0]="..."

    git_commit[1,0]="..."
    git_commit[1,1]="..."
    git_commit[1,2]="..."
    git_commit[1,3]="..."
    git_commit[1,4]="..."
    git_commit[1,5]="..."
    git_commit[1,6]="..."
    git_commit[1,7]="..."
    git_commit[1,8]="..."
    git_commit[1,9]="..."
    git_commit[1,10]="..."
    git_commit[1,11]="..."
    git_commit[1,12]="..."
    git_commit[1,13]="..."
    git_commit[1,14]="..."
    git_commit[1,15]="..."
    git_commit[1,16]="..."
    git_commit[1,17]="..."
    git_commit[1,18]="..."
    git_commit[1,19]="..."

## array sizes
    Ngit_dir[0]=0
    Ngit_dir[1]=19

## local-git pairs
    source_dir_git[0,0]=$base_dir/
    target_dir_git[0,0]=${git_dir[0]}/backup/
    alias_git[0,0]="backup_codeberg_git"
    
    source_dir_git[1,0]=$base_dir/nerd/dev/sh/bkp.sh/
    target_dir_git[1,0]=${git_dir[1]}/sh/bkp.sh/
    alias_git[1,0]="bkp_github_git"

    source_dir_git[1,1]=$base_dir/nerd/dev/sh/cvt.sh/
    target_dir_git[1,1]=${git_dir[1]}/sh/cvt.sh/
    alias_git[1,1]="cvt_github_git"

    source_dir_git[1,2]=$base_dir/nerd/dev/sh/ecl.sh/
    target_dir_git[1,2]=${git_dir[1]}/sh/ecl.sh/
    alias_git[1,2]="ecl_github_git"

    source_dir_git[1,3]=$base_dir/nerd/dev/sh/emutt.sh/
    target_dir_git[1,3]=${git_dir[1]}/sh/emutt.sh/
    alias_git[1,3]="emutt_github_git"
 
    source_dir_git[1,4]=$base_dir/nerd/dev/sh/pkg.sh/
    target_dir_git[1,4]=${git_dir[1]}/sh/pkg.sh/
    alias_git[1,4]="pkg_github_git"

    source_dir_git[1,5]=$base_dir/nerd/dev/sh/pm.sh/
    target_dir_git[1,5]=${git_dir[1]}/sh/pm.sh/
    alias_git[1,5]="pm_github_git"

    source_dir_git[1,6]=$base_dir/nerd/dev/sh/sw.sh/
    target_dir_git[1,6]=${git_dir[1]}/sh/sw.sh/
    alias_git[1,6]="sw_github_git"

    source_dir_git[1,7]=$base_dir/nerd/dev/sh/sync.sh/
    target_dir_git[1,7]=${git_dir[1]}/sh/sync.sh/
    alias_git[1,7]="sync_github_git"

    source_dir_git[1,8]=$base_dir/nerd/dev/sh/trsl.sh/
    target_dir_git[1,8]=${git_dir[1]}/sh/trsl.sh/
    alias_git[1,8]="trsl_github_git"

    source_dir_git[1,9]=$base_dir/nerd/dev/sh/web.sh/
    target_dir_git[1,9]=${git_dir[1]}/sh/web.sh/
    alias_git[1,9]="web_github_git"

    source_dir_git[1,10]=$base_dir/nerd/dev/sh/menu.sh/
    target_dir_git[1,10]=${git_dir[1]}/sh/menu.sh/
    alias_git[1,10]="menu_github_git"

    source_dir_git[1,11]=$base_dir/nerd/dev/vim/essence.vim/
    target_dir_git[1,11]=${git_dir[1]}/vim/essence.vim/
    alias_git[1,11]="essence_github_git"

    source_dir_git[1,12]=$base_dir/nerd/dev/vim/mpc.vim/
    target_dir_git[1,12]=${git_dir[1]}/vim/mpc.vim/
    alias_git[1,12]="mpc_github_git"

    source_dir_git[1,13]=$base_dir/nerd/dev/vim/org.vim/
    target_dir_git[1,13]=${git_dir[1]}/vim/org.vim/
    alias_git[1,13]="org_github_git"

    source_dir_git[1,14]=$base_dir/nerd/dev/vim/vimtex-colors.vim/
    target_dir_git[1,14]=${git_dir[1]}/vim/vimtex-colors.vim/
    alias_git[1,14]="vimtex_github_git"

    source_dir_git[1,15]=$base_dir/config/tex/preamble/
    target_dir_git[1,15]=${git_dir[1]}/config/tex/
    alias_git[1,15]="tex_github_git"

    source_dir_git[1,16]=$base_dir/config/linux/
    target_dir_git[1,16]=${git_dir[1]}/config/linux/
    alias_git[1,16]="linux_github_git"

    source_dir_git[1,17]=$base_dir/config/vim/vimrc
    target_dir_git[1,17]=${git_dir[1]}/config/vim/vimrc
    alias_git[1,17]="vimrc_github_git"

    source_dir_git[1,18]=$base_dir/config/vim/vimrc_keybind
    target_dir_git[1,18]=${git_dir[1]}/config/vim/vimrc_keybind
    alias_git[1,18]="vimrc_keybind_github_git"

    source_dir_git[1,19]=$base_dir/config/vim/vimrc_plugin
    target_dir_git[1,19]=${git_dir[1]}/config/vim/vimrc_plugin
    alias_git[1,19]="vimrc_plugin_github_git"
  
    source_dir_git[1,20]=$base_dir/nerd/doc/
    target_dir_git[1,20]=${git_dir[1]}/doc/
    alias_git[1,20]="doc_github_git"

    source_dir_git[1,21]=$base_dir/math/pdfs/
    target_dir_git[1,21]=${git_dir[1]}/math/
    alias_git[1,21]="pdfs_github_git"
   
## size array
    Ngit_st[0]=0
    Ngit_st[1]=21

